### ISSUE TITLE
New textures for 0.4.16

### ISSUE THREAD

**Issue by sporaxfr** [huynhpaul/vilja_pix#1]
![default_dirt_with_rainforest_litter_side](https://user-images.githubusercontent.com/21023919/29305441-1aedfa58-8199-11e7-8722-f6be76cb6baf.png)
![default_dirt_with_rainforest_litter](https://user-images.githubusercontent.com/21023919/29305452-2b2aaa10-8199-11e7-97e2-5a6ce00bbbda.png)
![default_silver_sandstone](https://user-images.githubusercontent.com/21023919/29305455-2f829316-8199-11e7-80cd-ca6b64a3ab02.png)
![default_silver_sandstone_block](https://user-images.githubusercontent.com/21023919/29305458-3555247a-8199-11e7-9bbb-f7034353411c.png)
![default_silver_sandstone_brick](https://user-images.githubusercontent.com/21023919/29305459-37a0132a-8199-11e7-994f-238febb86ac4.png)
![default_silver_sand](https://user-images.githubusercontent.com/21023919/29305462-39c3af04-8199-11e7-905f-962dd0555f3c.png)
![default_desert_sandstone_block](https://user-images.githubusercontent.com/21023919/29305471-466b42b2-8199-11e7-9215-e586b2f874f3.png)
![default_desert_sandstone_brick](https://user-images.githubusercontent.com/21023919/29305473-4818ff1e-8199-11e7-9b5c-24158bdc2e08.png)
![default_sandstone_block](https://user-images.githubusercontent.com/21023919/29305477-4a717430-8199-11e7-8b4b-6b9e12328a5a.png)
![default_desert_stone_block](https://user-images.githubusercontent.com/21023919/29305478-4c1bd938-8199-11e7-92ef-05f87bad1b68.png)
![default_mineral_tin](https://user-images.githubusercontent.com/21023919/29305479-4efc5506-8199-11e7-88f6-6fe5b65a08af.png)
![default_mese_post_light_top](https://user-images.githubusercontent.com/21023919/29305480-507ecd6e-8199-11e7-9929-fb087888ac14.png)
![default_mese_post_light_side](https://user-images.githubusercontent.com/21023919/29305485-51f1cbc4-8199-11e7-8311-9f73ad903e57.png)
![carts_cart](https://user-images.githubusercontent.com/21023919/29305486-544013d6-8199-11e7-93bc-6cce2abfea2c.png)
![carts_cart_top](https://user-images.githubusercontent.com/21023919/29305489-560384a0-8199-11e7-81b6-f9957cc34020.png)
![carts_cart_side](https://user-images.githubusercontent.com/21023919/29305491-57a55b4e-8199-11e7-9cb9-dddc4cd7a2c0.png)
![default_mese_post_light_side_dark](https://user-images.githubusercontent.com/21023919/29305520-6ff317d6-8199-11e7-8964-ef776b95fd3f.png)
![default_tin_block](https://user-images.githubusercontent.com/21023919/29305531-79ef7018-8199-11e7-834f-b40822e3880d.png)

**Comment by huynhpaul** [comment]
Salut Sporax, merci pour ton issue, peux-tu faire un pull request ? Les textures ont l'air correcte. Il faudra peut-être revoir celles du coffre pour avoir une identité visuelle unique.

**Comment by sporaxfr** [comment]
Salut KasBrick, je vais faire un pull request d'ici peu, contentque ces
textures soient à ton goût.
Pour les textures du 'coffre' de quoi parle tu exactement? Je ne me
souviens pas avoir mis des textures de coffres en issues...(peut etre
parles-tu des textures des carts!)

Bien a toi, Sporax

Le 21 oct. 2017 19:30, "HUÝNH" <notifications@github.com> a écrit :

Salut Sporax, merci pour ton issue, peux-tu faire un pull request ? Les
textures ont l'air correcte. Il faudra peut-être revoir celles du coffre
pour avoir une identité visuelle unique.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/huynhpaul/vilja_pix/issues/1#issuecomment-338419045>,
or mute the thread

**Comment by huynhpaul** [comment]
ça marche ;)
